ALTER TABLE Users
DROP CONSTRAINT PK__Users__3214EC07DDE2E514

ALTER TABLE Users
ADD PRIMARY KEY (Id, Username)

ALTER TABLE Users 
ADD CONSTRAINT Users_Password_CHK CHECK (DATALENGTH([Password]) >= 5)

ALTER TABLE Users
ADD CONSTRAINT Users_LastLoginTime_DF DEFAULT CURRENT_TIMESTAMP FOR LastLoginTime

ALTER TABLE Users
DROP CONSTRAINT PK__Users__77222459336218E5

ALTER TABLE Users
ADD PRIMARY KEY (Id)

ALTER TABLE Users 
ADD CONSTRAINT Users_Username_CHK CHECK (DATALENGTH(Username) >= 3)
